language: php

before_script:
    - composer self-update
    # using PHP 7 means stuff depending on ">=5.3.3" etc. breaks
    # so we make composer ignore it
    - composer install --dev --prefer-source --ignore-platform-reqs

php:
  - nightly
  - 7.1
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
